Psychtoolbox-3/Psychtoolbox-3

Psychtoolbox/PsychContributed/52-MyLinuxJoystick.conf, Psychtoolbox/PsychHardware/PsychGamepad/Gamepad.m
since Deban based systems apparently use xorg instead of xf86 now. 
I updated the instructions.
further reading
https://wiki.debian.org/Xorg
http://wiki.ubuntuusers.de/XServer
=> updated the instructions from xf86 to xserver for the gamepad.m 

PsychSourceGL/Source/Common/Screen/SCREENShowCursorHelper.c, Psychtoolbox/PsychBasic/ShowCursor.m
needed this, am building a selectable textbox for user input ;)
Untested as I don't have a build setup for psychtoolbox, but IDC_IBEAM is as found here: https://msdn.microsoft.com/en-us/library/windows/desktop/ms648391(v=vs.85).aspx
=> adding IBEAM cursor to selectable cursors in Windows

Psychtoolbox/PsychFiles/Var2Str.m, Psychtoolbox/PsychOneliners/Ask.m, Psychtoolbox/PsychTests/UnitTestRunAll.m, Psychtoolbox/PsychTests/UnitTests/Files_Test_FileFromFolder.m, Psychtoolbox/PsychTests/UnitTests/Files_Test_FileVar2Str.m, Psychtoolbox/PsychTests/UnitTests/Files_Test_LineTerminators.m, Psychtoolbox/PsychTests/UnitTests/Oneliners_Test_Structs.m
Running the unit tests i spotted one that failed on current matlab. Fixing Var2Str to address that. Fix would not affect older version that apparently don't produce 'Infi' values (hey, test used to pass...)
Also updated unit tests scripts a bit and random other typo fix
=> Small fixups

Psychtoolbox/Quest/QuestCreate.m
Formerly it misbehaved if tGuess was infinite, which can easily happen
if you guess zero and pass log(zero) as tGuess.
Contributed improvement by Denis Pelli.
=> QuestCreate: Validate tGuess being a finite real number value.

Psychtoolbox/PsychHardware/GetMouseIndices.m
Need to be able to select for slavePointers only on Linux
(option is ignored on other OSes), because if mice are
used with KbCheck/KbQueue et al., then those functions will
only work on slavePointers, not masterPointers.
=> GetMouseIndices: Add option 'slavePointers'

Psychtoolbox/PsychColorimetricData/ComputeCIEConeFundamentals.m, Psychtoolbox/PsychColorimetricData/ComputeRawConeFundamentals.m, Psychtoolbox/PsychColorimetricData/ShiftPhotopigmentAbsorbance.m
We have implemented the individual colorimetric observer model by Asano, Fairchild, & Blondé (2016), PLOS One [doi:10.1371/journal.pone.0145671] in the PTB cone fundamental/CIE machinery.
=> Merging of 'conefundamentals' dev branch with master branch

.travis.yml
For this to work, we should also (at least) make sure that `SetupPsychtoolbox.m` has correct exit status. `SetupPsychtoolbox.m` might not even be enough for the build tests. In that case, we could call a bash shell script which runs all necessary tests then exits with a meaningful status.
This script could be a good starting point to automate building and checking on different platforms (namely OSX and Linux) for Octave. Maybe we would even want to test Octave 3 and Octave 4 branches independently.
=> autobuild tests for Octave in Linux & OSX

PsychSourceGL/Cohorts/PsychtoolboxOSXKernelDriver/PsychtoolboxKernelDriver.cpp, PsychSourceGL/Source/Common/Screen/PsychGraphicsHardwareHALSupport.c, PsychSourceGL/Source/Linux/Screen/PsychScreenGlue.c, Psychtoolbox/PsychDemos/RaspberryPiGPIODemo.m, Psychtoolbox/PsychDocumentation/PTBSurvey.m, Psychtoolbox/PsychHardware/BitsPlusToolbox/BitsPlusTests/BitsPlusImagingPipelineTest.m, Psychtoolbox/PsychHardware/CMUBox.m, Psychtoolbox/PsychJava/PsychJavaSwingCleanup.m
* One time exec of PTBSurvey disables long nag screen.
* CMUBox Windows Vista+ compat fixes.
* BitsPlusImagingPipelineTest refinements for suboptimal setups.
* RaspberryPiGPIODemo: Add more infos about pin numbering.
=> Pull minor fixes for 3.0.13

Psychtoolbox/PsychOneliners/Ellipse.m, Psychtoolbox/PsychOneliners/Replace.m, Psychtoolbox/PsychProbability/RandLim.m
nargchk is deprecated in current matlabs, meaning you get a warning every time you use it.
Replaced with narginchk, which is supported since R2011b and also supported on Octave.
Tested on Octave as well.
Editing also added some empty newlines at ends of files that didn't have them, but that's good practice anyway.
=> replaced deprecated nargchk with narginchk

Psychtoolbox/PsychBasic/DrawFormattedText.m
The FTGL plugin internally uses a coordinate system with origin at bottom-left instead of top-left. We thus have to remap the position we flip the text around.
=> DrawFormattedText's flipVertical now works with FTGL plugin

Psychtoolbox/PsychHardware/PsychRTBox.m
The old RTbox website isn't accessible any more, the new site is located at http://lobes.osu.edu/rt-box.php
=> Update link to RTbox

Psychtoolbox/PsychColorimetricData/ComputeCIEConeFundamentals.m, Psychtoolbox/PsychColorimetricData/ComputeRawConeFundamentals.m, Psychtoolbox/PsychTests/CIEConeFundamentalsTest.m
These two commits make `ComputeCIEConeFundamentals` and `ComputeRawConeFundamentals` return the actual parameter values that the 'individual difference adjustment' provides (e.g. lens density would be returned as a density instead of the percentage-wise parametrization provided in the input)
=> Additional output arguments for cone fundamental functions

Psychtoolbox/PsychColorimetricData/ComputeCIEConeFundamentals.m, Psychtoolbox/PsychColorimetricData/ComputeRawConeFundamentals.m
This fixes an issue with the axial density for rods not being returned from the previous pull request.
=> ComputeCIEConeFundamentals and ComputeRawConeFundamentals now clean

PsychSourceGL/Source/Windows/PsychHID/PsychHIDStandardInterfaces.cpp
when computing cookedKey through ToAsciiEx:
- modifier press state is passed now, such that, e.g., Alt-Gr modifier works
- caps lock state is passed so thats taken into account
- when a dead char is in the keyboard buffer and a subsequent character is typed that does not combine with it, we now return the last typed character instead of nothing.
Also, now documenting all possible return values from ToAsciiEx (including -1 which is not in the docs) and having some debug code to simplify further work on this function.
Solves issue #373
=> Improve KbQueue's cooked key for MS-Windows

PsychSourceGL/Cohorts/FTGLTextRenderer/makeftglplugin.m
Because if system call contains a failure, but is run via bat file which itself completed successfully (i.e., the Windows build setup), we never see the output from the build as movefile fails.
=> makeftglplugin: display return of system call before movefile.

Psychtoolbox/PsychGLImageProcessing/Add2DConvolutionToGLOperator.m, Psychtoolbox/PsychGLImageProcessing/Add2DSeparableConvolutionToGLOperator.m, Psychtoolbox/PsychGLImageProcessing/AddImageUndistortionToGLOperator.m, Psychtoolbox/PsychGLImageProcessing/AddImageWarpToGLOperator.m
GLOperator's are proxy windows, which get initialize to have
zero size, ie. empty [0,0,0,0] rects. This causes an OpenGL
invalid value error in gluOrtho2D() when Screen('GetWindowInfo, gloperator);
trigger PsychSetDrawingTarget -> PsychSetupView -> gluOrtho2D(0,0,0,0,1,-1).
The proper fix is to give such proxy windows at least a [0,0,1,1] rect for
a 1x1 pixel size, but that would require a full recompile for Screen()
on all platforms.
Work around this by swallowing the error via glGetError() calls.
=> AddXXXToGLOperator: Add workaround for empty rects in gloperator's.

Psychtoolbox/PsychBasic/DrawFormattedText2.m, Psychtoolbox/PsychDemos/DrawFormattedText2Demo.m, Psychtoolbox/PsychOneliners/WrapString.m
- bugfix: now works with unicode text
- now by default draws to texture as cache instead of pregens sequence of drawtext calls: much better performance, and output looks nicer too when transforming (on my setup anyway, kinda strange really).
- redid wordbounds so that it works with this new cache as well
- properly dealing with empty input string or string containing only formatting directives (both now ignored)
- some comment fixes
=> DrawFormattedText2 enhancements

Psychtoolbox/PsychOneliners/MakeBeep.m
MakeBeep was off-by-one.
`a=MakeBeep(100,1,44100);` now actually generated a vector with 44100 samples.
=> fixing off-by-one error in length of output generated by MakeBeep

Psychtoolbox/PsychColorimetric/SPDToCCT.m
In the blackbody radiator calculation, `S` was defined as `[380 5 81]`, which breaks the code if `S_SPD` is passed into the function.
=> BF: 'S' specification fixed for BB calculation

Psychtoolbox/PsychBasic/DrawFormattedText2.m, Psychtoolbox/PsychDemos/DrawFormattedText2Demo.m
base color didn't actually work (weird!). Now have a test for it, and fixed it
=> DrawFormattedText2: fixed baseColor parameter

MANIFEST.in, setup.py
The inclusion of the license file is required e.g. when creating a package for `conda-forge`. Generally, it's always a good idea to include it. Closes #538.
=> PKG: Include license file in Python source distribution

Psychtoolbox/PsychHardware/Daq/Utilities/ConfirmInfo.m, Psychtoolbox/PsychHardware/Daq/Utilities/TwoStateQuery.m
Ha, fixed this somewhere on and old distro that didn't have your fixes from 2017 (they weren't willing to upgrade). In any case, GUI version of these now works with HG2. Have not tested with pre-hg2 matlabs as i don't have any. Is perhaps moot anyway, as I guess we don't really support those by now anymore?
=> ConfirmInfo and TwoStateQuery now work in GUI mode on R2014b and later

Psychtoolbox/PsychDemos/MinExpEntStairDemo.m, Psychtoolbox/PsychStairCase/MinExpEntStair.m
The interface is exactly the same, so existing user code should keep working (demo works identically without changes). The very briefly supported 'legacy' call syntax has however died now. Users using this are referred to the demo to learn the new syntax. Changes to code are minimal, e.g. stair('set_psychometric_func','logistic') -> stair.set_psychometric_func('logistic'), and thus easily executed.
=> ported MinExpEntStair.m to classdef, so it now also works in Octave

Psychtoolbox/PsychCal/MeasureDpi.m
- Included an optional input to request the user to use a ID/credit card instead of looking for an object. This can be handy as it is a common object of a known size.
- Included an output to request the drivers for the resolution and screen size. (It will only work on modern monitors with updated drivers).
=> - Use credit card and request to drivers.

Psychtoolbox/PsychBasic/DrawFormattedText2.m
With Octave 6, regexp expects strings to be truly UTF-8 encoded. This causes an "regexp: the input string is invalid UTF-8" error when calling DrawFormattedText2 with a vector that contains UTF character codes between 128 and 255, for example UTF-code 252 (umlaut-u). This can be easily reproduced with DrawFormattedText2Demo by inserting code 252 into the "unicodetext" vector near line 600.
As a workaround, we replace UTF codes >127 by zero rather than just replacing codes >255 by zero as it has been done so far.
This also works for Matlab.
=> DrawFormattedText2: Fix UTF-8 string handling WRT Octave 6

Psychtoolbox/PsychBasic/DrawFormattedText2.m, Psychtoolbox/PsychDemos/DrawFormattedText2Demo.m
DrawFormattedText2 didn't correctly capture the cached text in a texture when a transform is applied when creating the cache (text would be rendered outside the cache, meaning nothing showed up in it). Also added a test for this to DrawFormattedText2Demo
=> bugfix DrawFormattedText2 cache with transform

Psychtoolbox/PsychOneliners/LoadIdentityClut.m
In 07/10/17,  gfxhwtype=5 was introduced and chosen as default for AMD cards under Windows if GPUCoreId=='R600' and ditherApiVer==2. Back then, this fixed mapping glitches in the gamma table with "newer" graphics card drivers (for which ditherApiVer==2 was supposed to be an indicator). Meanwhile, this fix is not necessary anymore. In fact, now gfxhwtype=5 shows mapping glitches. Tested with several Win10 versions, AMD drivers, video ports (DP, DVI, DP++/DVI) and AMD cards (HD-7750, R7-250X, R7-260X, RX-550, RX-6400, WX-5100) - although not all combinations of these. 
The bottom line: nowadays, gfxhwtype=0 is always good, gfxhwtype=5 is mostly bad. 
If gfxhwtype=5 has glitches, it is always that the gamma table output is shifted by -1 within a code range starting at somewhere between 9 to …
=> AMD/Windows: Undo gfxhwtype=5 "fix"

Psychtoolbox/PsychBasic/DrawFormattedText.m
Fixes #817
I solved it by adding a new mode 'left'. This way exisitng code is not broken. The default value of 0 still refers to the left edge of the screen rather than of the `winRect`. Using `sx = 'left'`, it will take the left bound into consideration.
I just tested a few basic cases, here are the screenshots from it:
`DrawFormattedText` with `sx = 'left'` and a grey `winRect` offset to the right:
`DrawFormattedText` with `sx = 'left'` and a grey `winRect` offset to the left:
(more testing is probably required)
I used the same reproduce.m file as in the issue.
Just replaced `displayTextInRect(window, padding, 0);` with `displayTextInRect(window, padding, 'left');`
=> Add `'left'` option to `DrawFormattedText`s `sx` argument which positions text based on left `winRect` bound

Psychtoolbox/PsychColorimetricData/DegreesToRetinalEccentricityMM.m
Corrected the variable name from `eccMM` to `eccMm`. The typo was affecting the linear approximation functionality for small < .02 degree angles.
=> Fix typo in DegreesToRetinalEccentricityMM.m

PsychPython/psychtoolbox/audio.py
New PR with correct commit message.
Summary from the previous PR: 
Small change that prevents an AttributeError from being raised when the Stream.close() method is called. This occurs mostly when the __del__ method is called during garbage collection on a Stream object that encountered an error during initialization. When an error occurs inside the PsychPortAudio('Open', ...) command, the attribute handle is never created. When the object is garbage collected afterwards, there is a call to PsychPortAudio('Close', self.handle) but self.handle does not exist, resulting in an AttributeError.
This change simply checks if there is a self.handle attribute before calling PsychPortAudio('Close', ...).
=> Fix 'AttributeError' raised when creating a stream fails

Psychtoolbox/PsychDemos/BasicAMAndMixScheduleDemo.m, Psychtoolbox/PsychDemos/BasicSoundScheduleDemo.m, Psychtoolbox/PsychGLImageProcessing/PsychImaging.m, Psychtoolbox/PsychGLImageProcessing/PsychVulkan.m, Psychtoolbox/PsychHardware/BitsPlusToolbox/BitsPlusTests/BitsPlusIdentityClutTest.m, Psychtoolbox/PsychOneliners/Contents.m, Psychtoolbox/PsychOneliners/IsARM.m, Psychtoolbox/PsychTests/PsychPortAudioDataPixxTimingTest.m, Psychtoolbox/PsychTests/PsychPortAudioTimingTest.m, Psychtoolbox/PsychtoolboxPostInstallRoutine.m
- None
- None
- Psychtoolbox was built and tested against native Matlab R2024b and against native
Octave 9.3 from HomeBrew, on macOS 13.7.1 Ventura for Intel Macs, and on macOS 14.5
Sonoma for Apple Silicon Macs.
- Try to execute same code path on Apple Silicon macOS, regardless if running under native
Matlab/Octave for Apple Silicon ARM, or running under Intel Matlab/Octave via Rosetta2
emulation. Our license management aggregate stats tell us that a non-trivial fraction of users
still use Matlab for Intel Macs via Rosetta2 emulation on Apple Silicon, instead of the recommended
native Matlab/Octave for Apple Silicon. This would cause PTB to misbehave, as it would think it runs
on an Intel Mac and acts accordingly, instead of adapting to the special snowflake that is macOS on
Apple …
=> PTB beta update Psychtoolbox 3.0.20.1 "Appletizer SP1"

Psychtoolbox/PsychHardware/PR655Toolbox/PR655parsespdstr.m
`PR655parsespdstr` expects values to be 9 values long. 0 is encoded as `0.000e+000` however, which is 10 characters long, and this breaks the parser. This PR is a little tweak removes the final 0 of any `0.000e+000`s to make it 9 characters long.
I don't know whether this should be added to [the PR650 equivalent](https://github.com/Psychtoolbox-3/Psychtoolbox-3/blob/master/Psychtoolbox/PsychHardware/PR650Toolbox/PR650parsespdstr.m).
The parser works [differently for the PR670](https://github.com/Psychtoolbox-3/Psychtoolbox-3/blob/1d7b325a28b3f422bef17086d144694e9be9acd3/Psychtoolbox/PsychHardware/PR670Toolbox/PR670parsespdstr.m#L21-L42) and differently yet again for the [705](https://github.com/Psychtoolbox-3/Psychtoolbox-3/blob/1d7b325a28b3f422bef17086d144694e9be9acd3/Psychtoolbox/PsychHa …
=> Update PR655parsespdstr.m to handle zero values
